name: c14
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - python
  - pip
  - jupyter
  - jupyterlab
  - xlrd=1.2.0
  - pip:
    - openpyxl
    - iosacal



